version: '3.8'
services:
  ai_operator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
    networks:
      - ai_operator_network
    depends_on:
      - redis
  
  redis:
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - ai_operator_network

networks:
  ai_operator_network:
    driver: bridge